### ISSUE TITLE
restc不支持RESTful的accept方式控制版本号

### ISSUE THREAD

**Issue by changjunhao** [ElemeFE/restc#10]
必须
Accept: application/json, */*
Accept: application/vnd.github.v3+json
两个都写，不然会报错
虽然并不影响正常运行，但能否实现支持

**Comment by lujjjh** [comment]
谢谢，中间件的 Accept 检测方式确实需要改进。

**Comment by lujjjh** [comment]
暂时可以先用

```http
Accept: application/vnd.github.v3+json, */*
```
