### ISSUE TITLE
301/302 redirect page

### ISSUE THREAD

**Issue by jiananshi** [ElemeFE/restc#15]
Says we currently have an API redirects user to another page:

```
Request --> API --> PageA
```

**restc** send a request  from frontend with fetch instead of jumping page which breaks the process, currently I have to disable restc on prod env.

<img width="285" alt="2017-03-27 10 52 25" src="https://cloud.githubusercontent.com/assets/8141958/24339150/96593e0e-12dc-11e7-822f-853729f92ee5.png">

thanks in advance

**Comment by lujjjh** [comment]
Since this is a restriction of `fetch` and the `Location` of 30x is not exposed to the browser, I have no idea how to deal with it.

I am closing this issue. If there is solutions in the future, I will open this again.

**Comment by Fmain** [comment]
遇到了同样的问题
