### ISSUE TITLE
关于静态资源的引用

### ISSUE THREAD

**Issue by jinhuiWong** [ElemeFE/restc#25]
不支持加载本地js和css文件吗？内网用不了啊。。。。。。
![image](https://user-images.githubusercontent.com/23117130/30479757-47019e1a-9a49-11e7-9a80-eec594f9d356.png)

**Comment by lujjjh** [comment]
不能访问外网的话确实有问题。理论上全部内联就可以了，不过那样体积会很大，我再想想。

**Comment by gemmi** [comment]
这个问题现在有解决方案吗？我们也遇到了相同的问题，内网无法使用

**Comment by lujjjh** [comment]
@gemmi 请问你们接入用的是 nginx `proxy_pass` 的方案还是 Express / Koa 中间件的方案？

**Comment by YoungLee1992** [comment]
@lujjjh 怎么内联这些css和js啊 直接换路径编译后没法显示 浏览器解析后样式文件为空

**Comment by hewangjs** [comment]
同样遇到了这个问题，有没有破解的方法

**Comment by jinhuiWong** [comment]
人肉下载替换

**Comment by lujjjh** [comment]
Upgrade to `restc@^0.5.0` and use

```
restc.koa2({ inline: true })
```

to inline external stylesheets and scripts in HTML.
