### ISSUE TITLE
按照demo引入

### ISSUE THREAD

**Issue by magic007** [ElemeFE/restc#27]
写入 res.set('Content-Type', 'application/octet-stream')后
postman没问题，浏览器打开，直接下载一个文件后缀为dms

**Comment by lujjjh** [comment]
对二进制文件，restc 会显示一个「Download」按钮：

<img src="https://user-images.githubusercontent.com/3000535/35428112-4aa7c81a-02a8-11e8-91b6-6badca606cc1.png" width="319" height="198" />

如果浏览器打开直接下载了文件，可能是因为没有优先使用 restc 中间件。

建议把预期的结果描述得清晰一些。

**Comment by magic007** [comment]
明白了，已经解决。header强制 json就好了
