### ISSUE TITLE
eggjs中使用不生效

### ISSUE THREAD

**Issue by HbuJiaTian** [ElemeFE/restc#34]
你好，在eggjs中添加restc中间件，执行了但是并没有生效，请问是什么原因？代码是egg中写的中间件代码：
![wechatimg24](https://user-images.githubusercontent.com/10797390/43510894-a101c42e-95a9-11e8-991d-00b236d37d24.png)

**Comment by lujjjh** [comment]
我没有用过 egg，但是看起来与 Koa 的中间件是兼容的。或许你可以直接使用 `restc.koa2()`。

如果只希望应用于部分 URL，可以参考 #26。与截图中等价的配置是

```js
restc.koa2({ includes: /\/mock/ })
```

**Comment by HbuJiaTian** [comment]
已经解决了，需要封一层，谢谢

**Comment by lujjjh** [comment]
客气了。我先关闭这个 issue，还有问题可以随时打开。
