### ISSUE TITLE
KOA2 使用 想渲染html 时怎么弄？

### ISSUE THREAD

**Issue by 18978909244** [ElemeFE/restc#39]
静态文件使用没问题，但是用模版引擎渲染一些html而不是json接口时，依然会走restc的服务，这个时候怎么强制输出html？

**Comment by lujjjh** [comment]
如果 API 有固定前缀，可以针对某个前缀 `use` restc。

规则复杂的情况下可以用 `includes` / `excludes` / `shouldHandle`，请参考 #26 。
