### ISSUE TITLE
在firefox47.xx版本上，有css错误

### ISSUE THREAD

**Issue by wabomo** [ElemeFE/restc#4]
操作环境：win7，firefox47，
页面右侧工具栏有显示，页面左则内容为空白，其实接口有返回
![image](https://cloud.githubusercontent.com/assets/3222485/20659162/cc3599d6-b57c-11e6-872a-b2b57223cb90.png)
只在css栏有错误日志
![image](https://cloud.githubusercontent.com/assets/3222485/20659106/7db21bb8-b57c-11e6-9aff-3ee4fc234d40.png)

**Comment by lujjjh** [comment]
看起来是 Firefox 的一个 BUG，这里有讨论：
http://stackoverflow.com/questions/39285126/firefox-es6-get-class-constructor-name

It appears to be a bug in Firefox, and here's the discussion:
http://stackoverflow.com/questions/39285126/firefox-es6-get-class-constructor-name
