### ISSUE TITLE
Nginx方式配置报400

### ISSUE THREAD

**Issue by HQ1363** [ElemeFE/restc#41]
400.1 无匹配的主机名，页面出不来

**Comment by lujjjh** [comment]
需要看下 proxy_pass 的 Host 对不对，是否其他地方有 `proxy_set_header Host`？

**Comment by HQ1363** [comment]
location /server/v1/ {
                add_header Vary Accept;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                if ($http_accept ~* "text/html") {
                    rewrite ^.*$ / break;
                    proxy_pass https://restc.faas.ele.me;
                }
                proxy_pass http://127.0.0.1:8600/v1/;
        }

不清楚哪里不对？ 文档说的也不是很清楚。 特殊处：我的域名，可能仅办公网可访问

**Comment by lujjjh** [comment]
问题出在

```nginx
proxy_set_header Host $host;
```

重写掉了 proxy pass 到 restc.faas.ele.me 的 Host。

可以用 `if` 或者 `map` 解决这个问题，大致思路如下：

```nginx
set $x_host $host;
if ($http_accept ~* "text/html") {
  set $x_host $proxy_host;
}
proxy_set_header Host $x_host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

if ($http_accept ~* "text/html") {
  rewrite ^.*$ / break;
  proxy_pass https://restc.faas.ele.me;
}

proxy_pass http://127.0.0.1:8600/v1/;
```

**Comment by HQ1363** [comment]
👍， 解决了，thks
