### ISSUE TITLE
KOA2+webpack middleware +restc  运行问题

### ISSUE THREAD

**Issue by yuzukwok** [ElemeFE/restc#8]
webpack middleware与restc搭配一起运行，restc打开接口地址，直接提示下载，无法显示页面，response返回的content type 并不是txt/html 。

后面直接修改源代码，重新设定了响应的类型，之后正常

**Comment by lujjjh** [comment]
有没有可以复现的代码？Koa 对 string 默认的 Content-Type 就是 [`text/html` 或者 `text/plain`][1]，如果不是手动指定了其他 Content-Type，应该不需要显式指定成 text/html。

[1]: https://github.com/koajs/koa/blob/v2.x/lib/response.js#L152

**Comment by yuzukwok** [comment]
nodev7 https://github.com/yuzukwok/testkoarestc

**Comment by lujjjh** [comment]
你好，感谢提供可以重现的代码。

restc 的中间件应该在最前面引入，不然实际上会有两次请求，而且默认的 Content-Type 可能被覆盖。

所以 `dev-server.js` 中应该改为：

```javascript
// at line 16
var app = new koa();

// import restc
const restc = require('restc');
// use restc middleware
app.use(restc.koa2());

//webpack 开发中间件 （中间件）
app.use(webpackdev({
  compiler: compiler,
  config: webpackConfig,
// ...
```

**Comment by yuzukwok** [comment]
嗯 但是访问index.html 的话就被restc替换内容了

**Comment by lujjjh** [comment]
可以用 [`koa-mount`](https://github.com/koajs/mount/tree/next#mounting-middleware) 把 restc 挂到 `/api` 上。
